---
- hosts: "{{ HOSTS | default('control[0]') }}"
  connection: local
  vars:
    controller_hostname: "{{ hostvars[inventory_hostname].ansible_host }}"
    controller_validate_certs: false

  tasks:
  - name: Update the "satellite_source" source inventory
    ansible.controller.inventory_source_update:
      name: "satellite_source"
      inventory: "Workshop Inventory"
      organization: Default
