---
- name: Install and register insights
  hosts: "{{ HOSTS is defined | ternary(HOSTS, PREFIX|default('')+'*') }}"
  become: true
  gather_facts: false
  strategy: free

  tasks:
    - name: Install and register insights
      ansible.builtin.include_role:
        name: redhat.insights.insights_client
    - name: Install insights compliance
      ansible.builtin.include_role:
        name: redhat.insights.compliance
        tasks_from: install
