---
- name: install and register insights 
  hosts: "{{ HOSTS is defined | ternary(HOSTS, PREFIX|default('')+'*') }}"
  become: yes
  gather_facts: no
  strategy: free

  tasks:
    - name: install and register insights
      include_role:
        name: redhat.insights.insights_client
        
    - name: install insights compliance
      include_role:
        name: redhat.insights.compliance
        tasks_from: install

