---
- name: install and register insights 
  hosts: "{{ HOSTS is defined | ternary(HOSTS, PREFIX|default('')+'*') }}"
  become: yes

  tasks:
    - name: install and register insights
      include_role:
        name: redhat.insights.insights_client

    - name: Randomized 1 to 5 second startup delay
      command: |
        python3 -c "import time;import random;zzzzz=random.uniform(1.0,5.0);time.sleep(zzzzz);print(zzzzz)"

    - name: install insights compliance
      import_role:
        name: redhat.insights.compliance
        tasks_from: install

