---
# https://devpress.csdn.net/cicd/62ec1d2689d9027116a10320.html
- name: Deploy satellite_infra workloads Task Group
  block:
  - name: Increment retry count
    set_fact:
      retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"
  - name: Resume failed Satellite tasks after each failed attempt
    ansible.builtin.include_tasks: satellite_hammer_task_resume.yml
    when: retry_count | int != 0

  - name: deploy satellite_infra workloads
    ansible.builtin.include_role:
      name: "{{ satellite_infra_vars }}"
    loop: "{{ satellite_infra_workloads }}"
    loop_control:
      loop_var: satellite_infra_vars

  rescue:
    - fail:
        msg: Maximum retries of grouped tasks reached
      # initial try plus 4 retries = 5 total tries
      when: retry_count | int == 4

    - debug:
        msg: "satellite_infra workloads Task Group failed, retry count: {{ retry_count }}"

    - ansible.builtin.include_tasks: setup_satellite_infra_subtasks.yml
...