---
- redhat.satellite.content_view:
    username: "{{ username | default(omit) }}"
    password: "{{ password | default(omit) }}"
    server_url: "{{ server_url | default(omit) }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
    name: "{{ content.content_view }}"
    organization: "{{ satellite_organization }}"
    repositories: "{{ content.repositories }}"
    #repositories: "{{ content_temp_repositories }}"

- redhat.satellite.content_view_filter:
    username: "{{ username | default(omit) }}"
    password: "{{ password | default(omit) }}"
    server_url: "{{ server_url | default(omit) }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
    name: "{{ item.name }}"
    organization: "{{ satellite_organization }}"
    content_view: "{{ content.content_view }}"
    repositories: "{{ content.repositories }}"
    #repositories: "{{ content_temp_repositories }}"
    filter_type: "{{ item.type }}"
    start_date: "{{ item.start_date | d(omit) }}"
    end_date: "{{ item.end_date | d(omit) }}"
    types: "{{ item.types | d(omit) }}"
    date_type: "{{ item.date_type | d(omit) }}"
    inclusion: "{{ item.inclusion | d(False) }}"
    errata_id: "{{ item.errata_id | d(omit) }}"
    max_version: "{{ item.max_version | d(omit) }}"
    min_version: "{{ item.min_version | d(omit) }}"
    rule_name: "{{item.rule_name | d(omit) }}"
    version: "{{ item.version | d(omit) }}"
    description: "{{ item.description | d(omit) }}"
  when: content.filters is defined
  loop: "{{ content.filters }}"
